FROM ubuntu

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    pkg-config \
    build-essential \
    cmake \
    curl \
    wget \
    git \
    libjpeg-dev \
    libtiff5-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libxvidcore-dev \
    libx264-dev \
    libgtk-3-dev \
    libhdf5-serial-dev \
    graphviz \
    libopenblas-dev \
    libatlas-base-dev \
    gfortran \
    python-tk \
    python-imaging-tk \	
    libv4l-dev \
    python-pip \
    python-setuptools \
    python-dev

RUN pip install wheel
RUN pip install numpy
RUN pip install paho-mqtt

# Compile opencv from source
RUN export CMAKE_INSTALL_PREFIX=/usr/local
RUN cd /opt && git clone https://github.com/opencv/opencv.git
RUN cd /opt/opencv && mkdir build

RUN cd /opt/opencv/build && cmake -D CMAKE_BUILD_TYPE=RELEASE \
          -D CMAKE_INSTALL_PREFIX=/usr/local \
          -D WITH_CUDA=OFF \
          -D INSTALL_PYTHON_EXAMPLES=ON \
          -D BUILD_EXAMPLES=ON \
          -D WITH_TBB=ON \
          -D WITH_V4L=ON ..
RUN cd /opt/opencv/build && make -j4
RUN cd /opt/opencv/build && make install
